# import related dict.

In [35]:
import numpy as np 
from sklearn import preprocessing, neighbors
from sklearn.model_selection import cross_validate
import pandas as pd 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from matplotlib import style
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn import utils
from flask import Flask, render_template, flash, request, url_for


# read the data from survey

In [36]:
df1 = pd.read_excel('HANA.19.JAN.xlsx')

# check the shape and data

In [37]:
df1.shape

(240, 16)

In [38]:
df1.head()

4. Select your Study Program name  \
0                                      M.Sc. Komedia   
1  M.Sc. Computer Engineering (Intelligent Networ...   
2  M.Sc. Computer Engineering (Intelligent Networ...   
3  M.Sc. Computer Engineering (Intelligent Networ...   
4  M.Sc. Computer Engineering (Intelligent Networ...   

  6. Select the course name 8. What was the main language of the course?  \
0         Cloud, Web&Mobile                                       German   
1        Information Mining                                     Englisch   
2        Learning Analytics                                     Englisch   
3        Information Mining                                     Englisch   
4        Learning Analytics                                     Englisch   

  5. Select your Language Level [English]  \
0                                      B2   
1                                      B2   
2                                      B2   
3                                      B2   
4                                      B1   

  5. Select your Language Level [German]  \
0                                 Native   
1                                     B2   
2                                     C1   
3                                     B1   
4                                     B1   

   7. Rate your difficulty level of this course *  \
0                                               2   
1                                               4   
2                                               3   
3                                               4   
4                                               3   

  Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Lectures]  \
0                                                25%                                                                                            
1                                               100%                                                                                            
2                                               100%                                                                                            
3                                               100%                                                                                            
4                                               100%                                                                                            

  Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Exercises]  \
0                                                25%                                                                                             
1                                               100%                                                                                             
2                                                75%                                                                                             
3                                               100%                                                                                             
4                                               100%                                                                                             

  Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Online Self study]  \
0                                               100%                                                                                           
1                                               100%                                                                                           
2                                               100%                                                                                           
3                                             

# drop unrelated columns

In [39]:
df1.drop(['4. Select your Study Program name'], 1, inplace=True)

In [40]:
df1.shape

(240, 15)

# Which course would you like to predict

In [41]:
df2 = ['Learning Analytics']

In [42]:
df = df1[df1['6. Select the course name'].isin(df2)]

In [43]:
df.shape

(81, 15)

In [44]:
#df.drop((df.columns[0]), axis=0, inplace=True)

In [45]:
df.head()

6. Select the course name 8. What was the main language of the course?  \
2         Learning Analytics                                     Englisch   
4         Learning Analytics                                     Englisch   
5         Learning Analytics                                     Englisch   
7         Learning Analytics                                     Englisch   
20        Learning Analytics                                     Englisch   

   5. Select your Language Level [English]  \
2                                       B2   
4                                       B1   
5                                       B1   
7                                       B1   
20                                      B2   

   5. Select your Language Level [German]  \
2                                      C1   
4                                      B1   
5                                      B1   
7                                      B1   
20                                     C1   

    7. Rate your difficulty level of this course *  \
2                                                3   
4                                                3   
5                                                3   
7                                                3   
20                                               3   

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Lectures]  \
2                                                100%                                                                                            
4                                                100%                                                                                            
5                                                100%                                                                                            
7                                                100%                                                                                            
20                                                50%                                                                                            

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Exercises]  \
2                                                 75%                                                                                             
4                                                100%                                                                                             
5                                                100%                                                                                             
7                                                100%                                                                                             
20                                                75%                                                                                             

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Online Self study]  \
2                                                100%                                                                                           
4                                                100%                                                                                           
5                                                100%                                                                                           
7                                                100%                                                                                           
20                                                75%                                                                                           

   Select the learning method you fo

# after select the course, drop that column to model preperation

In [46]:
df.drop(['6. Select the course name'], axis=1, inplace=True)

/Users/hasanhalacli/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [47]:
df.drop(['7. Rate your difficulty level of this course *'], axis=1, inplace=True)

In [48]:
df.drop(['5. Select your Language Level [German]'], axis=1, inplace=True)

In [49]:
df.drop(['8. What was the main language of the course?'], axis=1, inplace=True)

In [50]:
df.head()

5. Select your Language Level [English]  \
2                                       B2   
4                                       B1   
5                                       B1   
7                                       B1   
20                                      B2   

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Lectures]  \
2                                                100%                                                                                            
4                                                100%                                                                                            
5                                                100%                                                                                            
7                                                100%                                                                                            
20                                                50%                                                                                            

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Exercises]  \
2                                                 75%                                                                                             
4                                                100%                                                                                             
5                                                100%                                                                                             
7                                                100%                                                                                             
20                                                75%                                                                                             

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Online Self study]  \
2                                                100%                                                                                           
4                                                100%                                                                                           
5                                                100%                                                                                           
7                                                100%                                                                                           
20                                                75%                                                                                           

   Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Group Study]  \
2                                                 75%                                                                                     
4                                                100%                                                                                     
5                                                100%                                                                                     
7                                                100%                                                                                     
20                                                75%                                                                                     

   How much did you participate in the course activity. (For Mobile phone users: Swipe to left to see 100%)  \
2                                                100%                                                         
4                                     

In [51]:
df.shape

(81, 11)

# we need integers for KNN

In [52]:
def handle_non_numerical_data(df):
    columns = df.columns.values
    for column in columns:
        text_digit_vals = {}
        def convert_to_int(val):
            return text_digit_vals[val]

        if df[column].dtype != np.int64 and df[column].dtype != np.float64:
            column_contents = df[column].values.tolist()
            unique_elements = set(column_contents)
            x = 0
            for unique in unique_elements:
                if unique not in text_digit_vals:
                    text_digit_vals[unique] = x
                    x+=1

            df[column] = list(map(convert_to_int, df[column]))

    return df

df = handle_non_numerical_data(df)
print(df.head())

    5. Select your Language Level [English]  \
2                                         1   
4                                         2   
5                                         2   
7                                         2   
20                                        1   

    Select the learning method you found helpful to score a good grade.(For Mobile phone users: Swipe to left to see 100%) [Attending Lectures]  \
2                                                   1                                                                                             
4                                                   1                                                                                             
5                                                   1                                                                                             
7                                                   1                                                                            

/Users/hasanhalacli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [53]:
df.shape

(81, 11)

# Features

In [54]:
X=np.array(df.drop(['Enter the grade you earned in this course. (If you failed, please write 0)'],axis=1))

In [55]:
X

array([[1, 1, 1, 3, 1, 3, 1, 2, 1, 2],
       [2, 1, 2, 3, 2, 2, 1, 1, 1, 1],
       [2, 1, 2, 3, 2, 2, 1, 1, 1, 1],
       [2, 1, 2, 3, 2, 2, 1, 1, 1, 1],
       [1, 0, 1, 2, 1, 1, 0, 1, 1, 0],
       [2, 0, 0, 4, 0, 1, 1, 2, 1, 0],
       [1, 0, 1, 2, 2, 1, 0, 1, 1, 0],
       [2, 0, 0, 1, 0, 1, 1, 2, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 2, 1, 0],
       [2, 0, 0, 1, 0, 0, 1, 2, 1, 0],
       [1, 1, 2, 0, 1, 0, 0, 3, 0, 2],
       [3, 3, 2, 0, 0, 2, 0, 3, 0, 3],
       [1, 3, 1, 2, 3, 0, 1, 3, 1, 0],
       [1, 1, 2, 3, 2, 3, 1, 3, 1, 2],
       [1, 3, 1, 3, 2, 2, 1, 2, 1, 1],
       [1, 1, 2, 3, 2, 3, 1, 2, 1, 2],
       [1, 0, 0, 3, 2, 0, 0, 0, 1, 0],
       [0, 3, 1, 2, 3, 0, 1, 3, 1, 0],
       [1, 3, 0, 2, 1, 3, 0, 2, 1, 2],
       [1, 1, 2, 2, 1, 3, 1, 2, 1, 2],
       [1, 3, 2, 0, 0, 2, 0, 3, 0, 3],
       [1, 0, 2, 1, 0, 1, 1, 2, 1, 0],
       [1, 3, 2, 2, 0, 2, 0, 3, 0, 3],
       [1, 0, 3, 4, 0, 1, 1, 2, 1, 0],
       [1, 1, 1, 3, 1, 3, 0, 3, 0, 2],
       [1, 1, 1, 2, 2, 3,

In [56]:
#X = preprocessing.scale(X)

# Label

In [57]:
y1=np.array(df['Enter the grade you earned in this course. (If you failed, please write 0)'])

In [58]:
y1

array([2.3, 1.5, 1.5, 1.5, 2. , 1. , 2. , 1. , 1. , 1.5, 1.5, 1.3, 1.7,
       2. , 2. , 3.3, 3.3, 3. , 4.5, 1.8, 1.3, 5. , 3. , 1. , 3. , 2.3,
       3. , 2.7, 3.3, 3. , 4.5, 1.8, 3. , 1. , 3. , 2.3, 2. , 2. , 3.3,
       2.3, 3. , 2.7, 3.3, 3. , 2.7, 3.3, 1. , 0. , 3.2, 2.7, 2. , 3. ,
       0. , 2.9, 2. , 2. , 3.3, 3.3, 1.7, 2.7, 1.8, 3. , 1. , 3. , 1. ,
       3. , 2.3, 3. , 2. , 2. , 3.3, 3.3, 1.7, 2.3, 1.8, 3. , 1. , 3. ,
       1. , 3. , 2.3])

In [59]:
#y = preprocessing.scale(y1)

In [60]:
#clf = KMeans(n_clusters=4)

# Get rid of the continous number with encoder

In [61]:
lab_enc = preprocessing.LabelEncoder()

In [62]:
y = lab_enc.fit_transform(y1)

In [63]:
y

array([ 7,  3,  3,  3,  6,  1,  6,  1,  1,  3,  3,  2,  4,  6,  6, 12, 12,
       10, 13,  5,  2, 14, 10,  1, 10,  7, 10,  8, 12, 10, 13,  5, 10,  1,
       10,  7,  6,  6, 12,  7, 10,  8, 12, 10,  8, 12,  1,  0, 11,  8,  6,
       10,  0,  9,  6,  6, 12, 12,  4,  8,  5, 10,  1, 10,  1, 10,  7, 10,
        6,  6, 12, 12,  4,  7,  5, 10,  1, 10,  1, 10,  7])

# fit the model

In [64]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [65]:
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

# prediction

In [66]:
predicted_note = neigh.predict([[1, 2, 0, 2, 3, 2, 1, 0, 1, 1]])
predicted_note

array([6])

# Inverse the prediction

In [67]:
z=lab_enc.inverse_transform([predicted_note])

/Users/hasanhalacli/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:273: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [68]:
print(z)

[2.]
